language: node_js
sudo: required
install: yarn install
node_js: '6'
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script: yarn test
dist: trusty