language: node_js
sudo: required
before_script:
- npm install -g bower polymer-cli@next
- polymer install
node_js: '6'
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- xvfb-run polymer test